"""Add missing layer1 tables

Revision ID: 467a346c5a36
Revises: 871791300455
Create Date: 2026-07-24 20:38:51.998509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467a346c5a36'
down_revision: Union[str, Sequence[str], None] = '871791300455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layer1_80g_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('donee_pan', sa.String(length=20), nullable=True),
    sa.Column('donee_name', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_bank_accounts',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('cumulative_repatriated_usd', sa.Numeric(), nullable=True),
    sa.Column('pending_repatriation_inr', sa.Numeric(), nullable=True),
    sa.Column('tds_deducted_on_nro_balance', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_bank_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_bf_losses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('fy', sa.String(length=20), nullable=True),
    sa.Column('amount_inr', sa.Numeric(), nullable=True),
    sa.Column('was_filed_before_due_date', sa.Boolean(), nullable=True),
    sa.Column('attributable_to_additional_dep_inr', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_business',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('has_business_income', sa.Boolean(), nullable=True),
    sa.Column('profession_type', sa.String(length=100), nullable=True),
    sa.Column('gst_registered', sa.Boolean(), nullable=True),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('turnover_cash', sa.Numeric(), nullable=True),
    sa.Column('turnover_bank', sa.Numeric(), nullable=True),
    sa.Column('books_maintained', sa.Boolean(), nullable=True),
    sa.Column('receipts_profession', sa.Numeric(), nullable=True),
    sa.Column('gross_receipts', sa.Numeric(), nullable=True),
    sa.Column('expenses_total', sa.Numeric(), nullable=True),
    sa.Column('depreciation', sa.Numeric(), nullable=True),
    sa.Column('net_profit', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_business_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('nature', sa.String(length=100), nullable=True),
    sa.Column('amount_inr', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_business_firms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('firm_pan', sa.String(length=20), nullable=True),
    sa.Column('salary_interest_inr', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_business_vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('tonnage', sa.Numeric(), nullable=True),
    sa.Column('months_owned', sa.Integer(), nullable=True),
    sa.Column('presumptive_income_inr', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_capital_gains',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('has_capital_gains', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_cg_buyback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('buyback_date', sa.Date(), nullable=True),
    sa.Column('shares_tendered', sa.Numeric(), nullable=True),
    sa.Column('buyback_price_per_share', sa.Numeric(), nullable=True),
    sa.Column('deemed_dividend_inr', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_cg_commodity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('commodity_name', sa.String(length=100), nullable=True),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('sell_price', sa.Numeric(), nullable=True),
    sa.Column('buy_price', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_cg_financial',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=50), nullable=True),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('sell_price', sa.Numeric(), nullable=True),
    sa.Column('buy_price', sa.Numeric(), nullable=True),
    sa.Column('brokerage', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_cg_property',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('sell_value', sa.Numeric(), nullable=True),
    sa.Column('stamp_duty_value', sa.Numeric(), nullable=True),
    sa.Column('buy_value', sa.Numeric(), nullable=True),
    sa.Column('brokerage', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_cg_unlisted',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('sell_price', sa.Numeric(), nullable=True),
    sa.Column('buy_price', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_compliance',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('form_10f_is_filed', sa.Boolean(), nullable=True),
    sa.Column('form_10f_ack_number', sa.String(length=100), nullable=True),
    sa.Column('s197_is_available', sa.Boolean(), nullable=True),
    sa.Column('s197_rate', sa.Numeric(), nullable=True),
    sa.Column('s197_start', sa.Date(), nullable=True),
    sa.Column('s197_end', sa.Date(), nullable=True),
    sa.Column('s197_covered_types', sa.JSON(), nullable=True),
    sa.Column('chapter_xiia_elected', sa.Boolean(), nullable=True),
    sa.Column('trc_document_uploaded', sa.Boolean(), nullable=True),
    sa.Column('trc_validity_start', sa.Date(), nullable=True),
    sa.Column('trc_validity_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_deductions',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('s80c_epf', sa.Numeric(), nullable=True),
    sa.Column('s80c_ppf', sa.Numeric(), nullable=True),
    sa.Column('s80c_elss', sa.Numeric(), nullable=True),
    sa.Column('s80c_lic', sa.Numeric(), nullable=True),
    sa.Column('s80c_home_loan', sa.Numeric(), nullable=True),
    sa.Column('s80c_nsc', sa.Numeric(), nullable=True),
    sa.Column('s80c_tuition', sa.Numeric(), nullable=True),
    sa.Column('s80c_sukanya', sa.Numeric(), nullable=True),
    sa.Column('s80c_fd', sa.Numeric(), nullable=True),
    sa.Column('s80c_stamp_duty', sa.Numeric(), nullable=True),
    sa.Column('s80ccc_lic_annuity', sa.Numeric(), nullable=True),
    sa.Column('s80ccd1_nps', sa.Numeric(), nullable=True),
    sa.Column('s80ccd1b_nps', sa.Numeric(), nullable=True),
    sa.Column('s80d_self_family_premium', sa.Numeric(), nullable=True),
    sa.Column('s80d_self_family_preventive', sa.Numeric(), nullable=True),
    sa.Column('s80d_parents_premium', sa.Numeric(), nullable=True),
    sa.Column('s80d_parents_senior', sa.Boolean(), nullable=True),
    sa.Column('s80d_parents_preventive', sa.Numeric(), nullable=True),
    sa.Column('s80d_parents_medical', sa.Numeric(), nullable=True),
    sa.Column('s80d_parents_health_insurance', sa.Boolean(), nullable=True),
    sa.Column('s80dd_has_disabled_dependents', sa.Boolean(), nullable=True),
    sa.Column('s80dd_disability_percentage', sa.Numeric(), nullable=True),
    sa.Column('s80ddb_has_disease', sa.Boolean(), nullable=True),
    sa.Column('s80ddb_patient_category', sa.String(length=50), nullable=True),
    sa.Column('s80ddb_medical_expenses', sa.Numeric(), nullable=True),
    sa.Column('s80u_has_disability', sa.Boolean(), nullable=True),
    sa.Column('s80u_disability_percentage', sa.Numeric(), nullable=True),
    sa.Column('s80gg_has_rent_paid_no_hra', sa.Boolean(), nullable=True),
    sa.Column('s80gg_rent_paid', sa.Numeric(), nullable=True),
    sa.Column('s80ggb_ggc_political', sa.Numeric(), nullable=True),
    sa.Column('s80tta_ttb_applicable', sa.String(length=50), nullable=True),
    sa.Column('s80tta_ttb_savings', sa.Numeric(), nullable=True),
    sa.Column('s80tta_ttb_fd_rd', sa.Numeric(), nullable=True),
    sa.Column('s80e_education_loan', sa.Numeric(), nullable=True),
    sa.Column('s80eea_ee_affordable_home', sa.Numeric(), nullable=True),
    sa.Column('s80eea_ee_sanction_date', sa.Date(), nullable=True),
    sa.Column('s80m_dividend_income', sa.Numeric(), nullable=True),
    sa.Column('s80m_dividend_distributed', sa.Numeric(), nullable=True),
    sa.Column('s80m_dividend', sa.Numeric(), nullable=True),
    sa.Column('s80iac', sa.Numeric(), nullable=True),
    sa.Column('s80la', sa.Numeric(), nullable=True),
    sa.Column('s80p', sa.Numeric(), nullable=True),
    sa.Column('s80qqb', sa.Numeric(), nullable=True),
    sa.Column('s80rrb', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_dtaa',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('tax_residency_country', sa.String(length=100), nullable=True),
    sa.Column('trc_status', sa.Boolean(), nullable=True),
    sa.Column('has_permanent_establishment_in_india', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_dtaa_elections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('income_type', sa.String(length=100), nullable=True),
    sa.Column('article_number', sa.String(length=50), nullable=True),
    sa.Column('treaty_rate', sa.Numeric(), nullable=True),
    sa.Column('trc_applies', sa.Boolean(), nullable=True),
    sa.Column('form_10f_applies', sa.Boolean(), nullable=True),
    sa.Column('pe_declaration_applies', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_fa_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('asset_category', sa.String(length=100), nullable=True),
    sa.Column('asset_status', sa.String(length=100), nullable=True),
    sa.Column('initial_value', sa.Numeric(), nullable=True),
    sa.Column('peak_balance', sa.Numeric(), nullable=True),
    sa.Column('closing_balance', sa.Numeric(), nullable=True),
    sa.Column('gross_proceeds', sa.Numeric(), nullable=True),
    sa.Column('income_foreign', sa.Numeric(), nullable=True),
    sa.Column('tax_foreign', sa.Numeric(), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(), nullable=True),
    sa.Column('dtaa_applied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_foreign_assets',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('has_foreign_assets', sa.Boolean(), nullable=True),
    sa.Column('total_lrs_remitted_this_fy_inr', sa.Numeric(), nullable=True),
    sa.Column('lrs_purpose', sa.String(length=255), nullable=True),
    sa.Column('has_received_foreign_income', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_house_property',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('has_house_property_income', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_hp_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('co_owned', sa.Boolean(), nullable=True),
    sa.Column('my_share', sa.Numeric(), nullable=True),
    sa.Column('ownership_status', sa.String(length=50), nullable=True),
    sa.Column('buyer_pan', sa.String(length=20), nullable=True),
    sa.Column('tenant_pan', sa.String(length=20), nullable=True),
    sa.Column('rent_received', sa.Numeric(), nullable=True),
    sa.Column('municipal_taxes', sa.Numeric(), nullable=True),
    sa.Column('nav', sa.Numeric(), nullable=True),
    sa.Column('standard_deduction', sa.Numeric(), nullable=True),
    sa.Column('interest_paid', sa.Numeric(), nullable=True),
    sa.Column('pre_construction_interest', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_losses_credits',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('has_brought_forward_losses', sa.Boolean(), nullable=True),
    sa.Column('s79_shareholding_change', sa.Boolean(), nullable=True),
    sa.Column('unabsorbed_depreciation_cf', sa.Numeric(), nullable=True),
    sa.Column('unabsorbed_dep_additional', sa.Numeric(), nullable=True),
    sa.Column('tds_already_deducted', sa.Numeric(), nullable=True),
    sa.Column('advance_tax_q1', sa.Numeric(), nullable=True),
    sa.Column('advance_tax_q2', sa.Numeric(), nullable=True),
    sa.Column('advance_tax_q3', sa.Numeric(), nullable=True),
    sa.Column('advance_tax_q4', sa.Numeric(), nullable=True),
    sa.Column('form_26as_uploaded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_other_sources',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('has_other_sources_income', sa.Boolean(), nullable=True),
    sa.Column('interest_savings_inr', sa.Numeric(), nullable=True),
    sa.Column('interest_fd_rd_inr', sa.Numeric(), nullable=True),
    sa.Column('interest_fd_rd_tds_inr', sa.Numeric(), nullable=True),
    sa.Column('interest_bonds_inr', sa.Numeric(), nullable=True),
    sa.Column('interest_bonds_tds_inr', sa.Numeric(), nullable=True),
    sa.Column('interest_on_it_refund_inr', sa.Numeric(), nullable=True),
    sa.Column('dividend_inr', sa.Numeric(), nullable=True),
    sa.Column('dividend_tds_inr', sa.Numeric(), nullable=True),
    sa.Column('gifts_above_50k_inr', sa.Numeric(), nullable=True),
    sa.Column('local_authority_s10_20_inr', sa.Numeric(), nullable=True),
    sa.Column('spousal_clubbing_s64_inr', sa.Numeric(), nullable=True),
    sa.Column('minor_child_exemption_inr', sa.Numeric(), nullable=True),
    sa.Column('lic_maturity_inr', sa.Numeric(), nullable=True),
    sa.Column('lic_maturity_tds_inr', sa.Numeric(), nullable=True),
    sa.Column('miscellaneous_income_inr', sa.Numeric(), nullable=True),
    sa.Column('angel_tax_premium_inr', sa.Numeric(), nullable=True),
    sa.Column('exempt_interest_ppf_epf_inr', sa.Numeric(), nullable=True),
    sa.Column('taxable_epf_interest_inr', sa.Numeric(), nullable=True),
    sa.Column('exempt_pf_withdrawal_inr', sa.Numeric(), nullable=True),
    sa.Column('exempt_nps_withdrawal_inr', sa.Numeric(), nullable=True),
    sa.Column('taxable_nps_withdrawal_inr', sa.Numeric(), nullable=True),
    sa.Column('family_pension_gross_inr', sa.Numeric(), nullable=True),
    sa.Column('winnings_lottery_gaming_inr', sa.Numeric(), nullable=True),
    sa.Column('online_gaming_winnings_inr', sa.Numeric(), nullable=True),
    sa.Column('unexplained_income_115BBE_inr', sa.Numeric(), nullable=True),
    sa.Column('has_agricultural_income', sa.Boolean(), nullable=True),
    sa.Column('agricultural_income_inr', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_profile',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('tax_regime', sa.String(length=10), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('residential_status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_salary',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('has_salary_income', sa.Boolean(), nullable=True),
    sa.Column('salary_income_inr', sa.Numeric(), nullable=True),
    sa.Column('exempt_allowances_inr', sa.Numeric(), nullable=True),
    sa.Column('perquisites_inr', sa.Numeric(), nullable=True),
    sa.Column('profit_in_lieu_inr', sa.Numeric(), nullable=True),
    sa.Column('gross_salary_inr', sa.Numeric(), nullable=True),
    sa.Column('pt_paid_inr', sa.Numeric(), nullable=True),
    sa.Column('entertainment_allowance_inr', sa.Numeric(), nullable=True),
    sa.Column('standard_deduction_inr', sa.Numeric(), nullable=True),
    sa.Column('net_taxable_salary_inr', sa.Numeric(), nullable=True),
    sa.Column('employer_type', sa.String(length=50), nullable=True),
    sa.Column('is_pwd', sa.Boolean(), nullable=True),
    sa.Column('basic_da_inr', sa.Numeric(), nullable=True),
    sa.Column('rent_paid_inr', sa.Numeric(), nullable=True),
    sa.Column('metro_city', sa.Boolean(), nullable=True),
    sa.Column('hra_received_inr', sa.Numeric(), nullable=True),
    sa.Column('lta_received_inr', sa.Numeric(), nullable=True),
    sa.Column('lta_exempt_inr', sa.Numeric(), nullable=True),
    sa.Column('children_education_received_inr', sa.Numeric(), nullable=True),
    sa.Column('children_education_exempt_inr', sa.Numeric(), nullable=True),
    sa.Column('hostel_received_inr', sa.Numeric(), nullable=True),
    sa.Column('hostel_exempt_inr', sa.Numeric(), nullable=True),
    sa.Column('transport_received_inr', sa.Numeric(), nullable=True),
    sa.Column('transport_exempt_inr', sa.Numeric(), nullable=True),
    sa.Column('is_eligible_for_esop_deferral', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('layer1_salary_esop',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('exercise_date', sa.Date(), nullable=True),
    sa.Column('fmv_at_exercise_inr', sa.Numeric(), nullable=True),
    sa.Column('exercise_price_inr', sa.Numeric(), nullable=True),
    sa.Column('shares_exercised', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residency_trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_cg_property_imp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('quarter_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['layer1_cg_property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_unique_constraint('uq_router_session', 'router_sessions', ['user_id', 'financial_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_router_session', 'router_sessions', type_='unique')
    op.drop_table('layer1_cg_property_imp')
    op.drop_table('residency_trips')
    op.drop_table('layer1_salary_esop')
    op.drop_table('layer1_salary')
    op.drop_table('layer1_profile')
    op.drop_table('layer1_other_sources')
    op.drop_table('layer1_losses_credits')
    op.drop_table('layer1_hp_properties')
    op.drop_table('layer1_house_property')
    op.drop_table('layer1_foreign_assets')
    op.drop_table('layer1_fa_rows')
    op.drop_table('layer1_dtaa_elections')
    op.drop_table('layer1_dtaa')
    op.drop_table('layer1_deductions')
    op.drop_table('layer1_compliance')
    op.drop_table('layer1_cg_unlisted')
    op.drop_table('layer1_cg_property')
    op.drop_table('layer1_cg_financial')
    op.drop_table('layer1_cg_commodity')
    op.drop_table('layer1_cg_buyback')
    op.drop_table('layer1_capital_gains')
    op.drop_table('layer1_business_vehicles')
    op.drop_table('layer1_business_firms')
    op.drop_table('layer1_business_entries')
    op.drop_table('layer1_business')
    op.drop_table('layer1_bf_losses')
    op.drop_table('layer1_bank_rows')
    op.drop_table('layer1_bank_accounts')
    op.drop_table('layer1_80g_rows')
    # ### end Alembic commands ###
