"""Initial schema

Revision ID: 871791300455
Revises: 
Create Date: 2026-07-20 17:56:09.496552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871791300455'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarter_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=False),
    sa.Column('quarter_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'financial_year', 'quarter_type', name='uq_quarter_entry')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('broker_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residency_data',
    sa.Column('quarter_id', sa.UUID(), nullable=False),
    sa.Column('live_tracking_active', sa.Boolean(), nullable=True),
    sa.Column('manual_days', sa.Integer(), nullable=True),
    sa.Column('final_india_residency_status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quarter_id')
    )
    op.create_table('router_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_tax_year', sa.String(length=4), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('is_indian_citizen', sa.Boolean(), nullable=True),
    sa.Column('is_pio_or_oci', sa.Boolean(), nullable=True),
    sa.Column('india_days', sa.Integer(), nullable=True),
    sa.Column('has_india_source_income_or_assets', sa.Boolean(), nullable=True),
    sa.Column('is_us_citizen', sa.Boolean(), nullable=True),
    sa.Column('has_green_card', sa.Boolean(), nullable=True),
    sa.Column('was_in_us_this_year', sa.Boolean(), nullable=True),
    sa.Column('us_days', sa.Integer(), nullable=True),
    sa.Column('has_us_source_income_or_assets', sa.Boolean(), nullable=True),
    sa.Column('liable_to_tax_in_another_country', sa.Boolean(), nullable=True),
    sa.Column('left_india_for_employment_this_year', sa.Boolean(), nullable=True),
    sa.Column('india_flag', sa.Boolean(), nullable=True),
    sa.Column('us_flag', sa.Boolean(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=20), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'financial_year'),
    sa.UniqueConstraint('user_id', 'financial_year', name='uq_router_session')
    )
    op.create_table('capital_gains_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('broker_name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=50), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['broker_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capital_gains_trades')
    op.drop_table('router_sessions')
    op.drop_table('residency_data')
    op.drop_table('broker_connections')
    op.drop_table('users')
    op.drop_table('quarter_entries')
    # ### end Alembic commands ###
